name: Angular-CI
env: 
  APP_NAME: "Ang-test"
  PACK_NAME: "Ang-deploy-ver-${{ github.sha }}"
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"
on:
  push:
    branches: "master" 


jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: clone Repo
        uses: actions/checkout@v3
        
        
      - name: PrintAppName
        run: |
          echo "Application name: ${{ env.APP_NAME }}"
          echo "Deploy package name: ${{ env.PACK_NAME }}"
          
      - name: Testing
        run: |
          cd angular 
          npm install 
          npm ci
          npm run test -- --no-watch --no-progress

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: clone Repo
        uses: actions/checkout@v3

      - name: build
        run: |
          cd angular 
          npm install 
          npm run build
                
          
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: LogInPackage
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: BuildAndPush
        uses: docker/build-push-action@v2
        with:
          context: ./angular
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
          
  notification:
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    if: always()
    steps: 
      - uses: martialonline/workflow-status@v2
        id: check

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:      
          server_address: smtp.gmail.com        
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: wainerred@gmail.com
          from: wainer_actions
          body: Build job of ${{github.repository}} completed - ${{ steps.check.outputs.status }}! Lead time -  long.
          
      - name: Workflow Duration Action
        uses: channyein87/workflow-duration-action@v1.16
        id: duration
        
      - name: Get the output of duration
        run: echo "The duration is ${{ steps.duration.outputs.duration }} seconds long."
          
