

name: Angular-CI
env: 
  APP_NAME: "myFlask"
  PACK_NAME: "flask-deploy-ver-${{ github.sha }}"
  
on:
  push:
    branches: "master" 


jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: clone Repo
        uses: actions/checkout@v1
        
      - name: version node
        run: node -v
        
      - name: Print application name
        run: |
          echo "Application name: ${{ env.APP_NAME }}"
          echo "Deploy package name: ${{ env.PACK_NAME }}"
      
      - name: Testing 
        run: |
          cd angular 
          npm install
          npm run build
          npm run test
        
        

        
     
 
