

name: Angular-CI
env: 
  APP_NAME: "myFlask"
  PACK_NAME: "flask-deploy-ver-${{ githab.sha}}"
  
on:
  push:
    branches: "master" 


jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: clone Repo
      - uses: actions/checkout@v1
      
      - name: Testing 
      - run: cd angular-react-starter/angular && npm run test && npm run coverage

 
