name: Angular-CI
env: 
  APP_NAME: "myFlask"
  PACK_NAME: "flask-deploy-ver-${{ github.sha }}"
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"
on:
  push:
    branches: "master" 


jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: clone Repo
        uses: actions/checkout@v3
        
        
      - name: PrintAppName
        run: |
          echo "Application name: ${{ env.APP_NAME }}"
          echo "Deploy package name: ${{ env.PACK_NAME }}"
          
      - name: Testing
        run: |
          cd angular 
          npm install 
          npm run test -- --no-watch --no-progress

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: clone Repo
        uses: actions/checkout@v3

      - name: build
        run: |
          cd angular 
          npm install 
          npm run build
                
          
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: LogInPackage
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: BuildAndPush
        uses: docker/build-push-action@v3
        with:
          context: ./angular
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
