name: Angular-CI
env: 
  APP_NAME: "Ang-test"
  PACK_NAME: "Ang-deploy-ver-${{ github.sha }}"
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"
on:
  push:
    branches: "master" 



jobs:
  test: 
    runs-on: ubuntu-latest



    steps:
      

      
      - name: clone Repo
        uses: actions/checkout@v3
        
        
      - name: PrintAppName
        run: |
          echo "Application name: ${{ env.APP_NAME }}"
          echo "Deploy package name: ${{ env.PACK_NAME }}"
          
      - name: Testing
        run: |
          cd angular 
          npm install 
          npm run test -- --no-watch --no-progress
          
          

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: clone Repo
        uses: actions/checkout@v3

      - name: build
        run: |
          cd angular 
          npm install 
          npm run build
               
          
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: LogInPackage
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: BuildAndPush
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./angular
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      




          

  notification:
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps: 
      - name: checkStatus
        uses: martialonline/workflow-status@v2
        id: check
        
      - name: print_time
        env: 
          JOB_START: $(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq ".created_at")
          JOB_END: $(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq ".updated_at")
        run: |
          echo START= $( date --data = ${{ env.JOB_START }} +"%s" )
          echo END= $( date --data = ${{ env.JOB_END }} +"%s" )
          
          echo TIME= $(END) - $(START)

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:      
          server_address: smtp.gmail.com        
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: wainerred@gmail.com
          from: wainer_actions
          body: Build job of ${{ env.IMAGE_NAME }} completed - ${{ steps.check.outputs.status }}! Lead time -  second long.
          
